### ISSUE TITLE
[Bug] 3,530 low severity vulnerabilities

### ISSUE THREAD

**Issue by atimoney** [creativetimofficial/ct-paper-dashboard-pro-react#10]
### Version
latest
### Reproduction link
https://github.com/creativetimofficial/ct-argon-dashboard-pro-react/issues/new
### Operating System
Windows 10
### Device
Laptop
### Browser & Version
Chrome
### Steps to reproduce
npm install
### What is expected?
no errors
### What is actually happening?
npm install results in 3,530 low severity vulnerabilities

---

**Comment by einazare** [comment]
Hello there, @atimoney ,

I am a bit confused by your issue, you have given us the following link: https://github.com/creativetimofficial/ct-argon-dashboard-pro-react/issues/new
The problems that I am having, is that the link points to open a new issue for the [Argon Dashboard PRO React](https://www.creative-tim.com/product/argon-dashboard-pro-react) product, while this issue was opened for the [Paper Dashboard PRO React](https://www.creative-tim.com/product/paper-dashboard-pro-react) product.
So, my question for now, would be, which of the two products are you actually using, the Paper or the Argon?

At the moment, you cannot do anything to change those `low severity vulnerabilities`, if you make any changes to our products dependencies, the product might break - we usually spend around 2-3 weeks on our updates to make sure that the updates are working properly. Those vulnerabilities do not break our code, and they are not actually vulnerabilities, they are dependencies of our own dependencies that are 1-2 months old.

Best,
Manu
