### ISSUE TITLE
[Bug] Last Header in the table is not aligned propperly

### ISSUE THREAD

**Issue by bnap00** [creativetimofficial/ct-paper-dashboard-pro-react#11]
### Version
1.2.0
### Reproduction link
https://demos.creative-tim.com/paper-dashboard-pro-react/#/admin/react-tables
### Operating System
all
### Device
desktop
### Browser & Version
all
### Steps to reproduce
No steps needed
### What is expected?
The last header in table should be aligned as others. 
### What is actually happening?
the last header is not aligned as others are

---
### Solution
if the last header is meant for actions and it has to look that way, 
there should be a prop to disable that

**Comment by einazare** [comment]
Hello there, @bnap00 ,

Thank you for your interest in working with our products.
That was done intentionally - do not ask me why, since I am a developer, but our Designers with years of experience have done the design like so.

If you want to change this, you can go inside `src/assets/scss/paper-dashboard/react/plugins/_plugin-react-table.scss` and delete the following bits of codes:
```
.ReactTable .rt-thead .rt-th:last-child{
  text-align: right;
}
```

After that, you need to go inside `src/views/tables/ReactTables.js` and change the following code from:
```
<div className="actions-right">
```
To:
```
<div>
```

Since this is not an actual bug, I'll close the issue.

Best,
Manu
